apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    repoURL: ingress-nginx-app.yml
    targetRevision: v1.14.4
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

